[general]
import = [
	"~/.config/alacritty/themes/catppuccin-mocha.toml"
]

[env]
TERM = "xterm-256color"

[terminal]
shell = "/usr/bin/zsh"

[window]
padding.x = 10
padding.y = 10
decorations = "None"
opacity = 0.9
blur = true

[font]
size = 12
normal.family = "MesloLGS Nerd Font Mono"
bold.family = "MesloLGS Nerd Font Mono"
italic.family = "MesloLGS Nerd Font Mono"
bold_italic.family = "MesloLGS Nerd Font Mono"
